-- Update existing countries to ISO 3166-1 alpha-2 format (lowercase)
UPDATE countries SET code = 'kr' WHERE code = 'KOR' OR name = 'South Korea';
UPDATE countries SET code = 'us' WHERE code = 'USA' OR name = 'United States';
UPDATE countries SET code = 'nl' WHERE code = 'NLD' OR name = 'Netherlands';
UPDATE countries SET code = 'ch' WHERE code = 'CHE' OR name = 'Switzerland';
UPDATE countries SET code = 'jp' WHERE code = 'JPN' OR name = 'Japan';
UPDATE countries SET code = 'de' WHERE code = 'DEU' OR name = 'Germany';
UPDATE countries SET code = 'no' WHERE code = 'NOR' OR name = 'Norway';
UPDATE countries SET code = 'au' WHERE code = 'AUS' OR name = 'Australia';
UPDATE countries SET code = 'fr' WHERE code = 'FRA' OR name = 'France';
UPDATE countries SET code = 'cn' WHERE code = 'CHN' OR name = 'China';
UPDATE countries SET code = 'se' WHERE code = 'SWE' OR name = 'Sweden';
UPDATE countries SET code = 'ca' WHERE code = 'CAN' OR name = 'Canada';
UPDATE countries SET code = 'at' WHERE code = 'AUT' OR name = 'Austria';
UPDATE countries SET code = 'it' WHERE code = 'ITA' OR name = 'Italy';
UPDATE countries SET code = 'ru' WHERE code = 'RUS' OR name = 'Russia';
UPDATE countries SET code = 'fi' WHERE code = 'FIN' OR name = 'Finland';
UPDATE countries SET code = 'cz' WHERE code = 'CZE' OR name = 'Czech Republic' OR name = 'Czechia';
UPDATE countries SET code = 'pl' WHERE code = 'POL' OR name = 'Poland';
UPDATE countries SET code = 'gb' WHERE code = 'GBR' OR name = 'Great Britain' OR name = 'United Kingdom';
UPDATE countries SET code = 'es' WHERE code = 'ESP' OR name = 'Spain';

-- Update all existing INSERT entries to use ISO 3166-1 alpha-2 format
INSERT INTO countries (code, name) VALUES
-- Europe
('al', 'Albania'),
('ad', 'Andorra'),
('am', 'Armenia'),
('az', 'Azerbaijan'),
('by', 'Belarus'),
('be', 'Belgium'),
('ba', 'Bosnia and Herzegovina'),
('bg', 'Bulgaria'),
('hr', 'Croatia'),
('cy', 'Cyprus'),
('dk', 'Denmark'),
('ee', 'Estonia'),
('ge', 'Georgia'),
('gr', 'Greece'),
('hu', 'Hungary'),
('is', 'Iceland'),
('ie', 'Ireland'),
('il', 'Israel'),
('kz', 'Kazakhstan'),
('xk', 'Kosovo'),
('lv', 'Latvia'),
('li', 'Liechtenstein'),
('lt', 'Lithuania'),
('lu', 'Luxembourg'),
('mt', 'Malta'),
('md', 'Moldova'),
('mc', 'Monaco'),
('me', 'Montenegro'),
('mk', 'North Macedonia'),
('pt', 'Portugal'),
('ro', 'Romania'),
('sm', 'San Marino'),
('rs', 'Serbia'),
('sk', 'Slovakia'),
('si', 'Slovenia'),
('tr', 'Turkey'),
('ua', 'Ukraine'),

-- Asia
('af', 'Afghanistan'),
('bh', 'Bahrain'),
('bd', 'Bangladesh'),
('bt', 'Bhutan'),
('bn', 'Brunei'),
('kh', 'Cambodia'),
('hk', 'Hong Kong'),
('in', 'India'),
('id', 'Indonesia'),
('ir', 'Iran'),
('iq', 'Iraq'),
('jo', 'Jordan'),
('kw', 'Kuwait'),
('kg', 'Kyrgyzstan'),
('la', 'Laos'),
('lb', 'Lebanon'),
('my', 'Malaysia'),
('mv', 'Maldives'),
('mn', 'Mongolia'),
('mm', 'Myanmar'),
('np', 'Nepal'),
('kp', 'North Korea'),
('om', 'Oman'),
('pk', 'Pakistan'),
('ps', 'Palestine'),
('ph', 'Philippines'),
('qa', 'Qatar'),
('sa', 'Saudi Arabia'),
('sg', 'Singapore'),
('lk', 'Sri Lanka'),
('sy', 'Syria'),
('tw', 'Taiwan'),
('tj', 'Tajikistan'),
('th', 'Thailand'),
('tl', 'Timor-Leste'),
('tm', 'Turkmenistan'),
('ae', 'United Arab Emirates'),
('uz', 'Uzbekistan'),
('vn', 'Vietnam'),
('ye', 'Yemen'),

-- Africa
('dz', 'Algeria'),
('ao', 'Angola'),
('bj', 'Benin'),
('bw', 'Botswana'),
('bf', 'Burkina Faso'),
('bi', 'Burundi'),
('cm', 'Cameroon'),
('cv', 'Cape Verde'),
('cf', 'Central African Republic'),
('td', 'Chad'),
('km', 'Comoros'),
('cg', 'Republic of the Congo'),
('cd', 'DR Congo'),
('ci', 'Côte d\'Ivoire (Ivory Coast)'),
('dj', 'Djibouti'),
('eg', 'Egypt'),
('gq', 'Equatorial Guinea'),
('er', 'Eritrea'),
('sz', 'Eswatini (Swaziland)'),
('et', 'Ethiopia'),
('ga', 'Gabon'),
('gm', 'Gambia'),
('gh', 'Ghana'),
('gn', 'Guinea'),
('gw', 'Guinea-Bissau'),
('ke', 'Kenya'),
('ls', 'Lesotho'),
('lr', 'Liberia'),
('ly', 'Libya'),
('mg', 'Madagascar'),
('mw', 'Malawi'),
('ml', 'Mali'),
('mr', 'Mauritania'),
('mu', 'Mauritius'),
('ma', 'Morocco'),
('mz', 'Mozambique'),
('na', 'Namibia'),
('ne', 'Niger'),
('ng', 'Nigeria'),
('rw', 'Rwanda'),
('st', 'São Tomé and Príncipe'),
('sn', 'Senegal'),
('sc', 'Seychelles'),
('sl', 'Sierra Leone'),
('so', 'Somalia'),
('za', 'South Africa'),
('ss', 'South Sudan'),
('sd', 'Sudan'),
('tz', 'Tanzania'),
('tg', 'Togo'),
('tn', 'Tunisia'),
('ug', 'Uganda'),
('zm', 'Zambia'),
('zw', 'Zimbabwe'),

-- Americas
('ag', 'Antigua and Barbuda'),
('ar', 'Argentina'),
('aw', 'Aruba'),
('bs', 'Bahamas'),
('bb', 'Barbados'),
('bz', 'Belize'),
('bm', 'Bermuda'),
('bo', 'Bolivia'),
('br', 'Brazil'),
('ky', 'Cayman Islands'),
('cl', 'Chile'),
('co', 'Colombia'),
('cr', 'Costa Rica'),
('cu', 'Cuba'),
('dm', 'Dominica'),
('do', 'Dominican Republic'),
('ec', 'Ecuador'),
('sv', 'El Salvador'),
('gd', 'Grenada'),
('gt', 'Guatemala'),
('gy', 'Guyana'),
('ht', 'Haiti'),
('hn', 'Honduras'),
('jm', 'Jamaica'),
('mx', 'Mexico'),
('ni', 'Nicaragua'),
('pa', 'Panama'),
('py', 'Paraguay'),
('pe', 'Peru'),
('pr', 'Puerto Rico'),
('kn', 'Saint Kitts and Nevis'),
('lc', 'Saint Lucia'),
('vc', 'Saint Vincent and the Grenadines'),
('sr', 'Suriname'),
('tt', 'Trinidad and Tobago'),
('uy', 'Uruguay'),
('ve', 'Venezuela'),
('vg', 'British Virgin Islands'),
('vi', 'United States Virgin Islands'),

-- Oceania
('as', 'American Samoa'),
('ck', 'Cook Islands'),
('fj', 'Fiji'),
('pf', 'French Polynesia'),
('gu', 'Guam'),
('ki', 'Kiribati'),
('mh', 'Marshall Islands'),
('fm', 'Micronesia'),
('nr', 'Nauru'),
('nz', 'New Zealand'),
('pw', 'Palau'),
('pg', 'Papua New Guinea'),
('ws', 'Samoa'),
('sb', 'Solomon Islands'),
('to', 'Tonga'),
('tv', 'Tuvalu'),
('vu', 'Vanuatu')

ON DUPLICATE KEY UPDATE code = VALUES(code);
