-- V8: Seed all world countries (ISO 3166-1 alpha-2) with translations (en, de, fr).
-- Uses INSERT IGNORE to skip any countries that already exist by code.

INSERT IGNORE INTO countries (code, name, name_en, name_de, name_fr) VALUES
('AF', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan'),
('AL', 'Albania', 'Albania', 'Albanien', 'Albanie'),
('DZ', 'Algeria', 'Algeria', 'Algerien', 'Algérie'),
('AD', 'Andorra', 'Andorra', 'Andorra', 'Andorre'),
('AO', 'Angola', 'Angola', 'Angola', 'Angola'),
('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Antigua und Barbuda', 'Antigua-et-Barbuda'),
('AR', 'Argentina', 'Argentina', 'Argentinien', 'Argentine'),
('AM', 'Armenia', 'Armenia', 'Armenien', 'Arménie'),
('AZ', 'Azerbaijan', 'Azerbaijan', 'Aserbaidschan', 'Azerbaïdjan'),
('BS', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas'),
('BH', 'Bahrain', 'Bahrain', 'Bahrain', 'Bahreïn'),
('BD', 'Bangladesh', 'Bangladesh', 'Bangladesch', 'Bangladesh'),
('BB', 'Barbados', 'Barbados', 'Barbados', 'Barbade'),
('BY', 'Belarus', 'Belarus', 'Weißrussland', 'Biélorussie'),
('BE', 'Belgium', 'Belgium', 'Belgien', 'Belgique'),
('BZ', 'Belize', 'Belize', 'Belize', 'Belize'),
('BJ', 'Benin', 'Benin', 'Benin', 'Bénin'),
('BT', 'Bhutan', 'Bhutan', 'Bhutan', 'Bhoutan'),
('BO', 'Bolivia', 'Bolivia', 'Bolivien', 'Bolivie'),
('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'Bosnie-Herzégovine'),
('BW', 'Botswana', 'Botswana', 'Botswana', 'Botswana'),
('BR', 'Brazil', 'Brazil', 'Brasilien', 'Brésil'),
('BN', 'Brunei', 'Brunei', 'Brunei', 'Brunei'),
('BG', 'Bulgaria', 'Bulgaria', 'Bulgarien', 'Bulgarie'),
('BF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso'),
('BI', 'Burundi', 'Burundi', 'Burundi', 'Burundi'),
('CV', 'Cape Verde', 'Cape Verde', 'Kap Verde', 'Cap-Vert'),
('KH', 'Cambodia', 'Cambodia', 'Kambodscha', 'Cambodge'),
('CM', 'Cameroon', 'Cameroon', 'Kamerun', 'Cameroun'),
('CF', 'Central African Republic', 'Central African Republic', 'Zentralafrikanische Republik', 'République centrafricaine'),
('TD', 'Chad', 'Chad', 'Tschad', 'Tchad'),
('CL', 'Chile', 'Chile', 'Chile', 'Chili'),
('CO', 'Colombia', 'Colombia', 'Kolumbien', 'Colombie'),
('KM', 'Comoros', 'Comoros', 'Komoren', 'Comores'),
('CG', 'Congo', 'Congo', 'Kongo', 'Congo'),
('CD', 'Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'Demokratische Republik Kongo', 'République démocratique du Congo'),
('CR', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica'),
('HR', 'Croatia', 'Croatia', 'Kroatien', 'Croatie'),
('CU', 'Cuba', 'Cuba', 'Kuba', 'Cuba'),
('CY', 'Cyprus', 'Cyprus', 'Zypern', 'Chypre'),
('DK', 'Denmark', 'Denmark', 'Dänemark', 'Danemark'),
('DJ', 'Djibouti', 'Djibouti', 'Dschibuti', 'Djibouti'),
('DM', 'Dominica', 'Dominica', 'Dominica', 'Dominique'),
('DO', 'Dominican Republic', 'Dominican Republic', 'Dominikanische Republik', 'République dominicaine'),
('EC', 'Ecuador', 'Ecuador', 'Ecuador', 'Équateur'),
('EG', 'Egypt', 'Egypt', 'Ägypten', 'Égypte'),
('SV', 'El Salvador', 'El Salvador', 'El Salvador', 'Salvador'),
('GQ', 'Equatorial Guinea', 'Equatorial Guinea', 'Äquatorialguinea', 'Guinée équatoriale'),
('ER', 'Eritrea', 'Eritrea', 'Eritrea', 'Érythrée'),
('EE', 'Estonia', 'Estonia', 'Estland', 'Estonie'),
('SZ', 'Eswatini', 'Eswatini', 'Eswatini', 'Eswatini'),
('ET', 'Ethiopia', 'Ethiopia', 'Äthiopien', 'Éthiopie'),
('FJ', 'Fiji', 'Fiji', 'Fidschi', 'Fidji'),
('GA', 'Gabon', 'Gabon', 'Gabun', 'Gabon'),
('GM', 'Gambia', 'Gambia', 'Gambia', 'Gambie'),
('GE', 'Georgia', 'Georgia', 'Georgien', 'Géorgie'),
('GH', 'Ghana', 'Ghana', 'Ghana', 'Ghana'),
('GR', 'Greece', 'Greece', 'Griechenland', 'Grèce'),
('GD', 'Grenada', 'Grenada', 'Grenada', 'Grenade'),
('GT', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala'),
('GN', 'Guinea', 'Guinea', 'Guinea', 'Guinée'),
('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau'),
('GY', 'Guyana', 'Guyana', 'Guyana', 'Guyana'),
('HT', 'Haiti', 'Haiti', 'Haiti', 'Haïti'),
('HN', 'Honduras', 'Honduras', 'Honduras', 'Honduras'),
('HU', 'Hungary', 'Hungary', 'Ungarn', 'Hongrie'),
('IS', 'Iceland', 'Iceland', 'Island', 'Islande'),
('IN', 'India', 'India', 'Indien', 'Inde'),
('ID', 'Indonesia', 'Indonesia', 'Indonesien', 'Indonésie'),
('IR', 'Iran', 'Iran', 'Iran', 'Iran'),
('IQ', 'Iraq', 'Iraq', 'Irak', 'Irak'),
('IE', 'Ireland', 'Ireland', 'Irland', 'Irlande'),
('IL', 'Israel', 'Israel', 'Israel', 'Israël'),
('JM', 'Jamaica', 'Jamaica', 'Jamaika', 'Jamaïque'),
('JO', 'Jordan', 'Jordan', 'Jordanien', 'Jordanie'),
('KZ', 'Kazakhstan', 'Kazakhstan', 'Kasachstan', 'Kazakhstan'),
('KE', 'Kenya', 'Kenya', 'Kenia', 'Kenya'),
('KI', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati'),
('KP', 'North Korea', 'North Korea', 'Nordkorea', 'Corée du Nord'),
('KW', 'Kuwait', 'Kuwait', 'Kuwait', 'Koweït'),
('KG', 'Kyrgyzstan', 'Kyrgyzstan', 'Kirgisistan', 'Kirghizistan'),
('LA', 'Laos', 'Laos', 'Laos', 'Laos'),
('LB', 'Lebanon', 'Lebanon', 'Libanon', 'Liban'),
('LS', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesotho'),
('LR', 'Liberia', 'Liberia', 'Liberia', 'Libéria'),
('LY', 'Libya', 'Libya', 'Libyen', 'Libye'),
('LI', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein'),
('LT', 'Lithuania', 'Lithuania', 'Litauen', 'Lituanie'),
('LU', 'Luxembourg', 'Luxembourg', 'Luxemburg', 'Luxembourg'),
('MG', 'Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar'),
('MW', 'Malawi', 'Malawi', 'Malawi', 'Malawi'),
('MY', 'Malaysia', 'Malaysia', 'Malaysia', 'Malaisie'),
('MV', 'Maldives', 'Maldives', 'Malediven', 'Maldives'),
('ML', 'Mali', 'Mali', 'Mali', 'Mali'),
('MT', 'Malta', 'Malta', 'Malta', 'Malte'),
('MH', 'Marshall Islands', 'Marshall Islands', 'Marshallinseln', 'Îles Marshall'),
('MR', 'Mauritania', 'Mauritania', 'Mauretanien', 'Mauritanie'),
('MU', 'Mauritius', 'Mauritius', 'Mauritius', 'Maurice'),
('MX', 'Mexico', 'Mexico', 'Mexiko', 'Mexique'),
('FM', 'Micronesia', 'Micronesia', 'Mikronesien', 'Micronésie'),
('MD', 'Moldova', 'Moldova', 'Moldau', 'Moldavie'),
('MC', 'Monaco', 'Monaco', 'Monaco', 'Monaco'),
('MN', 'Mongolia', 'Mongolia', 'Mongolei', 'Mongolie'),
('ME', 'Montenegro', 'Montenegro', 'Montenegro', 'Monténégro'),
('MA', 'Morocco', 'Morocco', 'Marokko', 'Maroc'),
('MZ', 'Mozambique', 'Mozambique', 'Mosambik', 'Mozambique'),
('MM', 'Myanmar', 'Myanmar', 'Myanmar', 'Myanmar'),
('NA', 'Namibia', 'Namibia', 'Namibia', 'Namibie'),
('NR', 'Nauru', 'Nauru', 'Nauru', 'Nauru'),
('NP', 'Nepal', 'Nepal', 'Nepal', 'Népal'),
('NI', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua'),
('NE', 'Niger', 'Niger', 'Niger', 'Niger'),
('NG', 'Nigeria', 'Nigeria', 'Nigeria', 'Nigéria'),
('MK', 'North Macedonia', 'North Macedonia', 'Nordmazedonien', 'Macédoine du Nord'),
('OM', 'Oman', 'Oman', 'Oman', 'Oman'),
('PK', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan'),
('PW', 'Palau', 'Palau', 'Palau', 'Palaos'),
('PA', 'Panama', 'Panama', 'Panama', 'Panama'),
('PG', 'Papua New Guinea', 'Papua New Guinea', 'Papua-Neuguinea', 'Papouasie-Nouvelle-Guinée'),
('PY', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay'),
('PE', 'Peru', 'Peru', 'Peru', 'Pérou'),
('PH', 'Philippines', 'Philippines', 'Philippinen', 'Philippines'),
('PT', 'Portugal', 'Portugal', 'Portugal', 'Portugal'),
('QA', 'Qatar', 'Qatar', 'Katar', 'Qatar'),
('RO', 'Romania', 'Romania', 'Rumänien', 'Roumanie'),
('RU', 'Russia', 'Russia', 'Russland', 'Russie'),
('RW', 'Rwanda', 'Rwanda', 'Ruanda', 'Rwanda'),
('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'Saint-Kitts-et-Nevis'),
('LC', 'Saint Lucia', 'Saint Lucia', 'St. Lucia', 'Sainte-Lucie'),
('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen', 'Saint-Vincent-et-les-Grenadines'),
('WS', 'Samoa', 'Samoa', 'Samoa', 'Samoa'),
('SM', 'San Marino', 'San Marino', 'San Marino', 'Saint-Marin'),
('ST', 'Sao Tome and Principe', 'Sao Tome and Principe', 'São Tomé und Príncipe', 'Sao Tomé-et-Principe'),
('SA', 'Saudi Arabia', 'Saudi Arabia', 'Saudi-Arabien', 'Arabie saoudite'),
('SN', 'Senegal', 'Senegal', 'Senegal', 'Sénégal'),
('RS', 'Serbia', 'Serbia', 'Serbien', 'Serbie'),
('SC', 'Seychelles', 'Seychelles', 'Seychellen', 'Seychelles'),
('SL', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone'),
('SG', 'Singapore', 'Singapore', 'Singapur', 'Singapour'),
('SI', 'Slovenia', 'Slovenia', 'Slowenien', 'Slovénie'),
('SB', 'Solomon Islands', 'Solomon Islands', 'Salomonen', 'Îles Salomon'),
('SO', 'Somalia', 'Somalia', 'Somalia', 'Somalie'),
('ZA', 'South Africa', 'South Africa', 'Südafrika', 'Afrique du Sud'),
('SS', 'South Sudan', 'South Sudan', 'Südsudan', 'Soudan du Sud'),
('ES', 'Spain', 'Spain', 'Spanien', 'Espagne'),
('LK', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
('SD', 'Sudan', 'Sudan', 'Sudan', 'Soudan'),
('SR', 'Suriname', 'Suriname', 'Suriname', 'Suriname'),
('SY', 'Syria', 'Syria', 'Syrien', 'Syrie'),
('TW', 'Taiwan', 'Taiwan', 'Taiwan', 'Taïwan'),
('TJ', 'Tajikistan', 'Tajikistan', 'Tadschikistan', 'Tadjikistan'),
('TZ', 'Tanzania', 'Tanzania', 'Tansania', 'Tanzanie'),
('TH', 'Thailand', 'Thailand', 'Thailand', 'Thaïlande'),
('TL', 'Timor-Leste', 'Timor-Leste', 'Osttimor', 'Timor oriental'),
('TG', 'Togo', 'Togo', 'Togo', 'Togo'),
('TO', 'Tonga', 'Tonga', 'Tonga', 'Tonga'),
('TT', 'Trinidad and Tobago', 'Trinidad and Tobago', 'Trinidad und Tobago', 'Trinité-et-Tobago'),
('TN', 'Tunisia', 'Tunisia', 'Tunesien', 'Tunisie'),
('TR', 'Turkey', 'Turkey', 'Türkei', 'Turquie'),
('TM', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', 'Turkménistan'),
('TV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
('UG', 'Uganda', 'Uganda', 'Uganda', 'Ouganda'),
('UA', 'Ukraine', 'Ukraine', 'Ukraine', 'Ukraine'),
('AE', 'United Arab Emirates', 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'Émirats arabes unis'),
('GB', 'United Kingdom', 'United Kingdom', 'Vereinigtes Königreich', 'Royaume-Uni'),
('UY', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay'),
('UZ', 'Uzbekistan', 'Uzbekistan', 'Usbekistan', 'Ouzbékistan'),
('VU', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu'),
('VE', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela'),
('VN', 'Vietnam', 'Vietnam', 'Vietnam', 'Viêt Nam'),
('YE', 'Yemen', 'Yemen', 'Jemen', 'Yémen'),
('ZM', 'Zambia', 'Zambia', 'Sambia', 'Zambie'),
('ZW', 'Zimbabwe', 'Zimbabwe', 'Simbabwe', 'Zimbabwe');

